general:
  file_path: E:\Projects\ASF\Boars_Project_data\model\input\compressed_gps_5min.csv
  tessellation_path: E:\Projects\ASF\Boars_Project_data\model\input\tessellation_pop.geojson
  output_path: E:\Projects\ASF\Boars_Project_data\out
  start_simulation: "2025-01-02 00:00:00"
  end_simulation: "2025-01-03 00:00:00"
  random_seed: 42

execution:
  run_markov: true
  run_epr: true
  run_ditras: true
  copy_config: true

markov:
  chain_length: 24
  time_slot: "1h"
  label_column: "labels"
  generate:
    enabled: true
    duration_hours: 48

epr:
  rho: 0.6
  gamma: 0.21
  beta: 0.8
  tau: 17
  min_waiting_time_minutes: 30
  tessellation_attractiveness_column: "population"
  generate:
    n_agents: 2
    save_output_trajectory: true
    output_filename_prefix: "epr_simulation"

ditras:
  rho: 0.3
  gamma: 0.21
  beta: 0.8
  tau: 17
  min_waiting_time_minutes: 20
  tessellation_attractiveness_column: "population"
  simulation_with_attractiveness_raster: true
  attractiveness_raster_path: E:\Projects\ASF\Boars_Project_data\model\input\raster\corine_model_3857.tif
  generate:
    n_agents: 5
    save_output_trajectory: true
    output_filename_prefix: "ditras_simulation"
